//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guitar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusicScore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MusicScore()
        {
            this.MusicScoreCollection = new HashSet<MusicScoreCollection>();
            this.MusicScoreComment = new HashSet<MusicScoreComment>();
            this.MusicScoreReply = new HashSet<MusicScoreReply>();
        }
    
        public int Ms_id { get; set; }
        public int User_id { get; set; }
        public string Ms_title { get; set; }
        public string Score { get; set; }
        public string Ms_img { get; set; }
        public string Ms_label { get; set; }
        public System.DateTime Ms_addtime { get; set; }
        public int ReadCount { get; set; }
        public int Collection { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusicScoreCollection> MusicScoreCollection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusicScoreComment> MusicScoreComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusicScoreReply> MusicScoreReply { get; set; }
    }
}
