//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guitar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_comment
    {
        public string id { get; set; }
        public string customer_id { get; set; }
        public string parent_comment_id { get; set; }
        public string content_id { get; set; }
        public Nullable<int> type { get; set; }
        public string content { get; set; }
        public string comment_date { get; set; }
        public string comment_time { get; set; }
        public Nullable<int> state { get; set; }
    }
}
