//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guitar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Video()
        {
            this.VideoCollection = new HashSet<VideoCollection>();
            this.VideoComment = new HashSet<VideoComment>();
            this.VideoReply = new HashSet<VideoReply>();
        }
    
        public int Vi_id { get; set; }
        public int User_id { get; set; }
        public string Vi_url { get; set; }
        public string Vi_title { get; set; }
        public string Vi_description { get; set; }
        public string Vi_img { get; set; }
        public string Vi_label { get; set; }
        public System.DateTime Vi_addtime { get; set; }
        public int ReadCount { get; set; }
        public int Collection { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VideoCollection> VideoCollection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VideoComment> VideoComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VideoReply> VideoReply { get; set; }
    }
}
